version: '3.8'

services:
  webhook-deployment:
    build: .
    container_name: webhook-deployment
    ports:
      - "9522:9522"
    volumes:
      - ./config.env:/app/.env
      - /var/www/html:/var/www/html  # Mount directory project
      - ./logs:/app/logs             # Mount logs directory
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge
